export const LANG = {
  EN: {
    'WIDGET.BAND.QUALIFYING_REVENUE': 'Qualifying Revenue:',
    'WIDGET.BAND.COMMISSION': 'Commission for this band:',
    'WIDGET.TOTAL_COMMISSION': 'Total Commission:',
    'WIDGET.TITLE': 'Commission calculator',
    'WIDGET.INPUT_LABEL': 'Revenue: ',
    'WIDGET.INPUT_BUTTON': 'Calculate',
    CURRENCY_SYMBOL: '£',
    PERCENT_SYMBOL: '%',
    PLUS_SYMBOL: '+',
    'WIDGET.LOADING': 'Loading',
    'WIDGET.ERROR_RATES': "Couldn't calculate commission, please try again",
    'WIDGET.BAND.TITLE': 'Earnings breakdown:',
    'WIDGET.BAND.FROM': 'From:',
    'WIDGET.BAND.TO': 'To:',
    'WIDGET.BAND.RATE': 'Rate:',
    'WIDGET.BAND.COMMISSION_SUB': 'Commission:',
  },
  FR: {
    'WIDGET.BAND.QUALIFYING_REVENUE': 'Qualifying Revenue:',
    'WIDGET.BAND.COMMISSION': 'Commission for this band:',
    'WIDGET.TOTAL_COMMISSION': 'Total Commission:',
    'WIDGET.TITLE': 'Commission calculator',
    'WIDGET.INPUT_LABEL': 'Revenue: ',
    'WIDGET.INPUT_BUTTON': 'Calculate',
    CURRENCY_SYMBOL: '€',
    PERCENT_SYMBOL: '%',
    PLUS_SYMBOL: '+',
    'WIDGET.LOADING': 'Loading',
    'WIDGET.ERROR_RATES': "Couldn't get commission rates, please try again",
    'WIDGET.BAND.TITLE': 'Earnings breakdown:',
    'WIDGET.BAND.FROM': 'From:',
    'WIDGET.BAND.TO': 'To:',
    'WIDGET.BAND.RATE': 'Rate:',
    'WIDGET.BAND.COMMISSION_SUB': 'Commission:',
  },
} as const;
